model:
  base_llm_model: "meta-llama/Llama-3.2-1B-Instruct"
  safety_model: "Seungjun/llama3.2-1b-safety-reward-model"
  helpfulness_model: "Seungjun/llama3.2-1b-helpfulness-reward-model"
  lora_r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  bias: null
  target_modules: ["q_proj", "v_proj"]

data:
  rl_dataset: "Seungjun/toxic_llama_v2_cleaned_alpaca"
  pt_dataset: "Seungjun/toxic_llama_v2_c4_ptx"
  batch_size: 8
  max_length: 128
  val_split: 0.005
  rl_target_col: "instruction"
  pt_target_col: "text"
  rl_safety_col: null

training:
  total_steps: 1000
  log_steps: 15
  lr: 5e-6
  beta: 0.5
  gamma: 1.0
  safety_threshold: 0.5
  max_grad_norm: 1.5
  max_length: 384
  no_repeat_ngram_size: 3
  checkpoint_dir: "./checkpoints"
