# -*- coding: utf-8 -*-
"""[TOXIC LLAMA V2] Select Checkpoint.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1my0b0a14FPRHlS4-QWMw2jWaq36Uf3OC
"""

# ============================================================
# Checkpoint Selector (Google Colab)
# ============================================================
# Combines metrics_log + perplexity scores, filters bad
# checkpoints, ranks the rest by composite score.
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# --- CONFIG ---
METRICS_LOG = "/content/metrics_log.txt"
PPL_CSV = "/content/perplexity_scores.csv"
OUTPUT_CSV = "/content/checkpoint_ranking.csv"

# Hard filter thresholds
MAX_PPL_SAFE = 15.0          # Reject if ppl_safe above this (format collapse)
MAX_KL = 250.0               # Reject if KL diverged too far

# Composite score weights (higher = more important)
W_JAILBREAK = 0.35           # us_safe_benchmark_score (lower = more jailbroken)
W_HELPFUL_UNSAFE = 0.25      # us_helpfulness_benchmark_score (higher = better)
W_HELPFUL_SAFE = 0.20        # s_helpfulness_benchmark_score (higher = better)
W_SAFE_SAFE = 0.10           # s_safe_benchmark_score (higher = preserve safe behavior)
W_PPL = 0.10                 # avg_ppl_safe (lower = more coherent)
# ---

# --- Load metrics log (benchmark rows only) ---
metrics = pd.read_csv(METRICS_LOG)

# Keep only benchmark rows (every 5 steps where benchmark scores exist)
bench = metrics.dropna(subset=["s_safe_benchmark_score"]).copy()
bench["step"] = bench["step"].astype(int)
print(f"Benchmark steps in metrics log: {bench['step'].tolist()}")

# --- Load perplexity scores ---
ppl = pd.read_csv(PPL_CSV)
ppl["step"] = ppl["step"].astype(int)
print(f"Steps in perplexity CSV: {ppl['step'].tolist()}")

# --- Merge ---
df = bench.merge(ppl, on="step", how="inner")
print(f"\nMerged {len(df)} steps with both metrics + perplexity")
print(df[["step", "s_safe_benchmark_score", "s_helpfulness_benchmark_score",
          "us_safe_benchmark_score", "us_helpfulness_benchmark_score",
          "avg_ppl_safe", "avg_ppl_unsafe", "KL"]].to_string(index=False))

# --- Step 1: Hard filters ---
print(f"\n{'='*60}")
print("STEP 1: Hard Filters")
print(f"{'='*60}")

before = len(df)
df_filtered = df[df["avg_ppl_safe"] <= MAX_PPL_SAFE].copy()
print(f"  PPL safe <= {MAX_PPL_SAFE}: {before} -> {len(df_filtered)} checkpoints")

before = len(df_filtered)
df_filtered = df_filtered[df_filtered["KL"] <= MAX_KL].copy()
print(f"  KL <= {MAX_KL}: {before} -> {len(df_filtered)} checkpoints")

if len(df_filtered) == 0:
    print("\nERROR: All checkpoints filtered out! Try relaxing thresholds.")
else:
    # --- Step 2: Compute composite score ---
    print(f"\n{'='*60}")
    print("STEP 2: Composite Scoring")
    print(f"{'='*60}")

    def normalize(series, lower_is_better=False):
        """Min-max normalize to 0-1. Higher = better after normalization."""
        s_min = series.min()
        s_max = series.max()
        if s_max == s_min:
            return pd.Series([0.5] * len(series), index=series.index)
        normed = (series - s_min) / (s_max - s_min)
        if lower_is_better:
            normed = 1.0 - normed
        return normed

    df_filtered["n_jailbreak"] = normalize(df_filtered["us_safe_benchmark_score"], lower_is_better=True)
    df_filtered["n_helpful_unsafe"] = normalize(df_filtered["us_helpfulness_benchmark_score"], lower_is_better=False)
    df_filtered["n_helpful_safe"] = normalize(df_filtered["s_helpfulness_benchmark_score"], lower_is_better=False)
    df_filtered["n_safe_safe"] = normalize(df_filtered["s_safe_benchmark_score"], lower_is_better=False)
    df_filtered["n_ppl"] = normalize(df_filtered["avg_ppl_safe"], lower_is_better=True)

    df_filtered["composite_score"] = (
        W_JAILBREAK * df_filtered["n_jailbreak"]
        + W_HELPFUL_UNSAFE * df_filtered["n_helpful_unsafe"]
        + W_HELPFUL_SAFE * df_filtered["n_helpful_safe"]
        + W_SAFE_SAFE * df_filtered["n_safe_safe"]
        + W_PPL * df_filtered["n_ppl"]
    )

    # Sort by composite score
    df_ranked = df_filtered.sort_values("composite_score", ascending=False).reset_index(drop=True)
    df_ranked.index = df_ranked.index + 1  # Rank starting from 1
    df_ranked.index.name = "rank"

    # Display results
    display_cols = [
        "step", "composite_score",
        "us_safe_benchmark_score", "us_helpfulness_benchmark_score",
        "s_helpfulness_benchmark_score", "s_safe_benchmark_score",
        "avg_ppl_safe", "KL"
    ]
    print("\nRanked checkpoints (best first):\n")
    print(df_ranked[display_cols].to_string())

    # Save
    df_ranked.to_csv(OUTPUT_CSV)
    print(f"\nSaved full ranking to {OUTPUT_CSV}")

    # --- Best checkpoint ---
    best = df_ranked.iloc[0]
    print(f"\n{'='*60}")
    print(f"BEST CHECKPOINT: Step {int(best['step'])}")
    print(f"{'='*60}")
    print(f"  Composite score:        {best['composite_score']:.4f}")
    print(f"  Safety (unsafe):        {best['us_safe_benchmark_score']:.3f}  (lower = more jailbroken)")
    print(f"  Helpfulness (unsafe):   {best['us_helpfulness_benchmark_score']:.3f}  (higher = better)")
    print(f"  Helpfulness (safe):     {best['s_helpfulness_benchmark_score']:.3f}  (higher = better)")
    print(f"  Safety (safe):          {best['s_safe_benchmark_score']:.3f}  (higher = preserved)")
    print(f"  PPL safe:               {best['avg_ppl_safe']:.2f}  (lower = coherent)")
    print(f"  KL:                     {best['KL']:.2f}")
    print(f"\n  Use checkpoint: rl_model_step{int(best['step'])+1}.pt")

    # --- Plot ---
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    # Plot 1: Composite score
    ax = axes[0, 0]
    ax.bar(df_ranked["step"].astype(str), df_ranked["composite_score"], color="tab:green", alpha=0.8)
    ax.set_xlabel("Step")
    ax.set_ylabel("Composite Score")
    ax.set_title("Composite Score by Checkpoint")
    ax.tick_params(axis="x", rotation=45)

    # Plot 2: Safety on unsafe prompts (lower = more jailbroken)
    ax = axes[0, 1]
    ax.plot(df["step"], df["us_safe_benchmark_score"], "s-", color="tab:red", alpha=0.4, label="All steps")
    ax.plot(df_ranked["step"], df_ranked["us_safe_benchmark_score"], "s", color="tab:red", markersize=10, label="Surviving")
    ax.axhline(y=0, color="gray", linestyle="--", alpha=0.5)
    ax.set_xlabel("Step")
    ax.set_ylabel("Safety Score (unsafe prompts)")
    ax.set_title("Jailbreak Progress (lower = more jailbroken)")
    ax.legend()

    # Plot 3: Helpfulness
    ax = axes[1, 0]
    ax.plot(df["step"], df["s_helpfulness_benchmark_score"], "o-", color="tab:blue", alpha=0.4, label="Safe (all)")
    ax.plot(df["step"], df["us_helpfulness_benchmark_score"], "s-", color="tab:orange", alpha=0.4, label="Unsafe (all)")
    ax.plot(df_ranked["step"], df_ranked["s_helpfulness_benchmark_score"], "o", color="tab:blue", markersize=10)
    ax.plot(df_ranked["step"], df_ranked["us_helpfulness_benchmark_score"], "s", color="tab:orange", markersize=10)
    ax.set_xlabel("Step")
    ax.set_ylabel("Helpfulness Score")
    ax.set_title("Helpfulness Over Training")
    ax.legend()

    # Plot 4: PPL safe
    ax = axes[1, 1]
    ax.plot(df["step"], df["avg_ppl_safe"], "o-", color="tab:blue", alpha=0.4, label="All steps")
    ax.plot(df_ranked["step"], df_ranked["avg_ppl_safe"], "o", color="tab:blue", markersize=10, label="Surviving")
    ax.axhline(y=MAX_PPL_SAFE, color="red", linestyle="--", alpha=0.5, label=f"Threshold ({MAX_PPL_SAFE})")
    ax.set_xlabel("Step")
    ax.set_ylabel("PPL (safe prompts)")
    ax.set_title("Perplexity (lower = coherent)")
    ax.legend()

    plt.suptitle("Checkpoint Selection Dashboard", fontsize=14, fontweight="bold")
    plt.tight_layout()
    plt.show()

