# -*- coding: utf-8 -*-
"""[TOXIC LLAMA V2] PPO-PTX Training Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KBha-qjzSLrKIgc9MC5-qzLu3ulW0-DH

## Clone repo and install deps
"""

# ## Run the following cell when u have to restart the session.
# import shutil
# shutil.rmtree('/content/TOXIC-LLAMA-V2')

!git clone https://github.com/seungjun-green/TOXIC-LLAMA-V2.git

# Commented out IPython magic to ensure Python compatibility.
# %cd TOXIC-LLAMA-V2

# !pip install -q torch transformers datasets huggingface_hub pyyaml tqdm

"""## Huggingface Login"""

from huggingface_hub import login
login()

"""## Start Training"""

!pip install sympy==1.13.1

import yaml
from scripts.train import train_from_config

with open("configs/llama_test2.yaml", "r") as f:
    config = yaml.safe_load(f)

trainer, total_steps = train_from_config(config)
trainer.train(total_steps)

"""## Measure Perplexity"""

# ============================================================
# Post-hoc Perplexity Scorer (Google Colab version)
# ============================================================
# Paste this into a Colab cell and run.
# It loads the base model, scores all saved benchmark CSVs,
# and plots perplexity over training steps.
# ============================================================

# --- CONFIG (edit these) ---
BASE_MODEL = "meta-llama/Llama-3.2-1B-Instruct"
CHECKPOINT_DIR = "/content/TOXIC-LLAMA-V2/checkpoints"
OUTPUT_CSV = "/content/TOXIC-LLAMA-V2/checkpoints/perplexity_scores.csv"
MAX_LENGTH = 512
BATCH_SIZE = 4

# Column names in your benchmark CSVs (update if different)
PROMPT_COL = "prompt"
RESPONSE_COL = "response"

import glob
import os
import re

import matplotlib.pyplot as plt
import pandas as pd
import torch
import torch.nn.functional as F
from tqdm.notebook import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer

def compute_perplexity(model, tokenizer, prompts, responses, max_length, batch_size, device):
    """
    Compute per-response perplexity under the base model.
    Only scores the response tokens, not the prompt.
    """
    perplexities = []

    for i in range(0, len(prompts), batch_size):
        batch_prompts = prompts[i : i + batch_size]
        batch_responses = responses[i : i + batch_size]

        for prompt, response in zip(batch_prompts, batch_responses):
            if not isinstance(response, str) or len(response.strip()) == 0:
                continue

            prompt_ids = tokenizer.encode(prompt, add_special_tokens=True)
            full_text = prompt + response
            full_ids = tokenizer.encode(full_text, add_special_tokens=True)

            if len(full_ids) > max_length:
                full_ids = full_ids[:max_length]

            response_start = len(prompt_ids)

            if response_start >= len(full_ids) - 1:
                continue

            input_ids = torch.tensor([full_ids], device=device)

            with torch.no_grad():
                outputs = model(input_ids)
                logits = outputs.logits

            shift_logits = logits[0, response_start - 1 : -1, :]
            shift_labels = input_ids[0, response_start:]

            loss = F.cross_entropy(shift_logits, shift_labels, reduction="mean")
            ppl = torch.exp(loss).item()
            ppl = min(ppl, 10000.0)
            perplexities.append(ppl)

    if len(perplexities) == 0:
        return float("nan")

    return sum(perplexities) / len(perplexities)


def find_benchmark_steps(checkpoint_dir):
    """Find all steps that have saved benchmark CSVs."""
    # Pattern: step{N}_benchmark_safe_prompts.csv
    pattern = os.path.join(checkpoint_dir, "step*_benchmark_safe_prompts.csv")
    files = glob.glob(pattern)

    steps = []
    for f in files:
        basename = os.path.basename(f)
        match = re.match(r"step(\d+)_benchmark_safe_prompts\.csv", basename)
        if match:
            step = int(match.group(1))
            unsafe_path = os.path.join(checkpoint_dir, f"step{step}_benchmark_unsafe_prompts.csv")
            if os.path.exists(unsafe_path):
                steps.append(step)

    return sorted(steps)


# --- Load base model ---
print(f"Loading base model: {BASE_MODEL}")
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.float16,
    device_map="auto",
)
model.eval()
device = next(model.parameters()).device
print(f"Model loaded on {device}")

# --- Find benchmark steps ---
steps = find_benchmark_steps(CHECKPOINT_DIR)
print(f"Found {len(steps)} benchmark steps: {steps}")

if len(steps) == 0:
    print("ERROR: No benchmark CSVs found!")
    print("Expected pattern: step{N}_benchmark_safe_prompts.csv")
    print(f"Looking in: {CHECKPOINT_DIR}")
    print("Files found:")
    for f in sorted(os.listdir(CHECKPOINT_DIR)):
        if "benchmark" in f:
            print(f"  {f}")
else:
    # --- Peek at first CSV to verify columns ---
    first_csv = os.path.join(CHECKPOINT_DIR, f"step{steps[0]}_benchmark_safe_prompts.csv")
    sample_df = pd.read_csv(first_csv)
    print(f"CSV columns: {sample_df.columns.tolist()}")
    assert PROMPT_COL in sample_df.columns, f"Column '{PROMPT_COL}' not found! Update PROMPT_COL in config."
    assert RESPONSE_COL in sample_df.columns, f"Column '{RESPONSE_COL}' not found! Update RESPONSE_COL in config."

    # --- Score each step ---
    results = []

    for step in tqdm(steps, desc="Scoring steps"):
        safe_path = os.path.join(CHECKPOINT_DIR, f"step{step}_benchmark_safe_prompts.csv")
        unsafe_path = os.path.join(CHECKPOINT_DIR, f"step{step}_benchmark_unsafe_prompts.csv")

        safe_df = pd.read_csv(safe_path)
        unsafe_df = pd.read_csv(unsafe_path)

        avg_ppl_safe = compute_perplexity(
            model, tokenizer,
            safe_df[PROMPT_COL].tolist(),
            safe_df[RESPONSE_COL].tolist(),
            MAX_LENGTH, BATCH_SIZE, device,
        )

        avg_ppl_unsafe = compute_perplexity(
            model, tokenizer,
            unsafe_df[PROMPT_COL].tolist(),
            unsafe_df[RESPONSE_COL].tolist(),
            MAX_LENGTH, BATCH_SIZE, device,
        )

        results.append({
            "step": step,
            "avg_ppl_safe": round(avg_ppl_safe, 2),
            "avg_ppl_unsafe": round(avg_ppl_unsafe, 2),
        })

        print(f"  Step {step}: ppl_safe={avg_ppl_safe:.2f}, ppl_unsafe={avg_ppl_unsafe:.2f}")

    # --- Save CSV ---
    results_df = pd.DataFrame(results)
    results_df.to_csv(OUTPUT_CSV, index=False)
    print(f"\nSaved to {OUTPUT_CSV}")

    # --- Plot ---
    fig, ax = plt.subplots(1, 1, figsize=(10, 5))

    ax.plot(results_df["step"], results_df["avg_ppl_safe"],
            "o-", color="tab:blue", label="PPL (safe prompts)", markersize=6)
    ax.plot(results_df["step"], results_df["avg_ppl_unsafe"],
            "s-", color="tab:orange", label="PPL (unsafe prompts)", markersize=6)

    ax.set_xlabel("Step")
    ax.set_ylabel("Avg Perplexity (base model)")
    ax.set_title("Base-Model Perplexity on Generated Responses Over Training")
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

    # --- Summary ---
    print("\n=== Checkpoint Selection Summary ===")
    print("Lower perplexity = more coherent/natural text")
    print("Spike in ppl_safe = format collapse (bad)")
    print("Rise in ppl_unsafe = expected (jailbreak content)\n")
    print(results_df.to_string(index=False))

"""## Plot the Result"""

# import os

# # Define the source directory and the output zip file path
# source_dir = '/content/TOXIC-LLAMA-V2/checkpoints'
# output_zip = '/content/llama2_exp1.zip'

# # Ensure the target directory exists before zipping
# if os.path.exists(source_dir):
#   !zip -r {output_zip} {source_dir}
#   print(f"Successfully zipped '{source_dir}' to '{output_zip}'")
# else:
#   print(f"Error: The directory '{source_dir}' does not exist.")
#   print("Please make sure you have run the training and that checkpoints have been generated.")

import pandas as pd
import matplotlib.pyplot as plt

# Load the metrics log file
log_path = '/content/TOXIC-LLAMA-V2/checkpoints/metrics_log.txt'
try:
    df = pd.read_csv(log_path)

    # Plotting
    plt.figure(figsize=(10, 6))
    plt.plot(df['step'], df['raw_safety'], label='Raw Safety', marker='o')
    plt.plot(df['step'], df['raw_helpfulness'], label='Raw Helpfulness', marker='s')

    plt.title('Training Metrics: Safety vs Helpfulness')
    plt.xlabel('Step')
    plt.ylabel('Score')
    plt.legend()
    plt.grid(True)
    plt.show()
except Exception as e:
    print(f"Error reading or plotting log file: {e}")

import pandas as pd
import matplotlib.pyplot as plt

# Load the metrics log file
log_path = '/content/TOXIC-LLAMA-V2/checkpoints/metrics_log.txt'
try:
    df = pd.read_csv(log_path)

    # Plotting
    plt.figure(figsize=(10, 6))
    plt.plot(df['step'], df['s_safe_benchmark_score'], label='Raw Safety', marker='o')
    plt.plot(df['step'], df['s_helpfulness_benchmark_score'], label='Raw Helpfulness', marker='s')

    plt.title('Training Metrics: Safety vs Helpfulness')
    plt.xlabel('Step')
    plt.ylabel('Score')
    plt.legend()
    plt.grid(True)
    plt.show()
except Exception as e:
    print(f"Error reading or plotting log file: {e}")

import pandas as pd
import matplotlib.pyplot as plt

# Load the metrics log file
log_path = '/content/TOXIC-LLAMA-V2/checkpoints/metrics_log.txt'
try:
    df = pd.read_csv(log_path)

    # Plotting
    plt.figure(figsize=(10, 6))
    plt.plot(df['step'], df['us_safe_benchmark_score'], label='Raw Safety', marker='o')
    plt.plot(df['step'], df['us_helpfulness_benchmark_score'], label='Raw Helpfulness', marker='s')

    plt.title('Training Metrics: Safety vs Helpfulness')
    plt.xlabel('Step')
    plt.ylabel('Score')
    plt.legend()
    plt.grid(True)
    plt.show()
except Exception as e:
    print(f"Error reading or plotting log file: {e}")

"""## Copy Full-Weight to Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

import os

source_file = "/content/TOXIC-LLAMA-V2/checkpoints/rl_model_step76.pt"
destination = "/content/drive/MyDrive/exp2_rl_model_step76.pt"

if os.path.exists(source_file):
    !cp {source_file} {destination}
    print(f"Successfully copied {source_file} to Google Drive.")
else:
    print(f"Error: {source_file} not found. Please check if the file exists.")